import {audio} from './sound.mjs';
import{Game,W,H,largestOnes,oneGroups}from'./tiles-engine.mjs';
const ITEM_INFO={};
const $=id=>document.getElementById(id),colors=['','#e7e1d8','#f2bdb7','#f3d29d','#eadf9c','#bbd9bd','#afd6db','#bacbea','#cdbfe5','#e5bfda'],ink=['','#766c5d','#824b48','#7d6139','#746932','#466b4a','#416c74','#49648a','#68528a','#855578'];let game=new Game(),started=false,paused=false,last=0,soft=false,held={},rulePause=false,lastEvent=null,touchColumn=null,touchPointer=null,touchActive=null;
for(let i=0;i<2;i++)$('gauge'+i).innerHTML='<i></i>';
function tile(ctx,x,y,n,{alpha=1,ghost=false,attack=false,active=false,item=null,simple=false}={}){ctx.save();ctx.globalAlpha=alpha;let xx=x*80+5,yy=y*80+5;let paint=ctx.createLinearGradient(0,yy,0,yy+70);paint.addColorStop(0,colors[n]);paint.addColorStop(1,colors[n]);ctx.fillStyle=ghost?'#edf1e9':paint;ctx.shadowColor=ghost?'transparent':'#48645022';ctx.shadowBlur=3;ctx.shadowOffsetY=3;ctx.beginPath();ctx.roundRect(xx,yy,70,70,12);ctx.fill();ctx.shadowBlur=0;ctx.shadowOffsetY=0;ctx.strokeStyle=ghost?'#a8bcac':attack?'#936978':active?'#456d55':'#ffffff99';ctx.lineWidth=ghost?2:active?4:2;if(ghost)ctx.setLineDash([5,5]);ctx.stroke();ctx.setLineDash([]);if(!ghost){ctx.strokeStyle='#ffffff85';ctx.lineWidth=2;ctx.beginPath();ctx.roundRect(xx+3,yy+3,64,64,10);ctx.stroke();ctx.fillStyle='#ffffff60';ctx.fillRect(xx+12,yy+4,46,2);ctx.fillStyle=ink[n];ctx.font='800 55px sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';if(!simple)ctx.fillText(n,xx+35,yy+37);if(n===1&&!simple){ctx.fillStyle='#9b8060';ctx.font='bold 19px sans-serif';ctx.fillText('✷',xx+56,yy+15)}if(item){ctx.fillStyle=ITEM_INFO[item].color;ctx.beginPath();ctx.roundRect(xx+43,yy+3,24,23,6);ctx.fill();ctx.fillStyle='#fff';ctx.font='bold 20px sans-serif';ctx.fillText(ITEM_INFO[item].mark,xx+55,yy+15)}if(attack){ctx.fillStyle='#8d6378';ctx.beginPath();ctx.arc(xx+59,yy+10,4,0,7);ctx.fill()}}ctx.restore()}
function draw(i){let b=game.boards[i],c=$('board'+i),ctx=c.getContext('2d');ctx.clearRect(0,0,640,1040);ctx.fillStyle='#f8faf6';ctx.fillRect(0,0,640,1040);for(let y=0;y<H;y++)for(let x=0;x<W;x++){ctx.fillStyle=(x+y)%2?'#edf2eb':'#f0f4ee';ctx.beginPath();ctx.roundRect(x*80+3,y*80+3,74,74,9);ctx.fill();let t=b.g[y][x];if(t)tile(ctx,x,y,t.n,{attack:t.attack,item:t.item,simple:i===1})}ctx.fillStyle='#adc6b655';ctx.fillRect(3*80+15,2,50,5);for(let p of b.incoming)if(p.remaining!==null){tile(ctx,p.x,p.y,p.n,{alpha:.2+.7*(1-p.remaining/(p.duration||3000)),attack:true,item:p.item,simple:i===1});ctx.fillStyle='#684b65';ctx.font='bold 18px sans-serif';ctx.textAlign='right';if(i===0)ctx.fillText((Math.max(0,p.remaining)/1000).toFixed(1),p.x*80+72,p.y*80+72)}if(i===0&&touchColumn!==null){ctx.fillStyle='#9ec9a244';ctx.fillRect(touchColumn*80,0,80,1040);let y=game.landing(b,touchColumn,0);if(y>=0&&b.active)tile(ctx,touchColumn,y,b.active.n,{ghost:true})}if(b.active){let a=b.active,y=game.landing(b,a.x,a.y);if(y!==a.y)tile(ctx,a.x,y,a.n,{ghost:true});tile(ctx,a.x,a.y,a.n,{active:true,item:a.item,simple:i===1})}if(i===0){let groups=oneGroups(b.g),size=groups[0]?.length||0;if(size>=2)for(let [index,group] of groups.filter(v=>v.length===size).entries()){let set=new Set(group);ctx.save();ctx.strokeStyle=['#bd964b','#629c96','#a37dac'][index%3];ctx.lineWidth=5;ctx.shadowColor=ctx.strokeStyle;ctx.shadowBlur=size>=8?10+5*Math.sin(game.time/180):6;ctx.globalAlpha=size>=8?.8+.2*Math.sin(game.time/180):.85;for(let k of group){let x=k%W*80,y=Math.floor(k/W)*80;ctx.beginPath();if(!set.has(k-W)){ctx.moveTo(x+4,y+4);ctx.lineTo(x+76,y+4)}if(!set.has(k+W)){ctx.moveTo(x+4,y+76);ctx.lineTo(x+76,y+76)}if(k%W===0||!set.has(k-1)){ctx.moveTo(x+4,y+4);ctx.lineTo(x+4,y+76)}if(k%W===W-1||!set.has(k+1)){ctx.moveTo(x+76,y+4);ctx.lineTo(x+76,y+76)}ctx.stroke()}ctx.restore()}}if(b.busy){ctx.fillStyle='#ffffffbb';for(let k of b.flash)ctx.fillRect((k%8)*80+5,Math.floor(k/8)*80+5,70,70)}$('gaugeText'+i).innerHTML=b.gauge+' <small>/ 20</small>';let meter=$('gauge'+i);meter.firstElementChild.style.width=(b.gauge/20*100)+'%';meter.setAttribute('role','progressbar');meter.setAttribute('aria-label',i===0?'내 공격 스택':'상대 공격 스택');meter.setAttribute('aria-valuemin','0');meter.setAttribute('aria-valuemax','20');meter.setAttribute('aria-valuenow',String(b.gauge));let connected=largestOnes(b.g);$('effects'+i).innerHTML='<span class="one-progress">✷ 1 연결 <b>'+connected.length+'/10</b></span><span class="one-track"><i style="width:'+Math.min(100,connected.length*10)+'%"></i></span>';$('incoming'+i).textContent='도착 예정 '+b.incoming.length;$('note'+i).textContent=b.note;if(i===1){let first=b.g.findIndex(row=>row[3]),height=first<0?0:H-first;$('riskFill').style.height=(height/H*100)+'%';$('risk').classList.toggle('danger',height>=H-3);$('risk').setAttribute('aria-label','중앙 열 높이 '+height+'/'+H)}}
function render(){draw(0);draw(1);let t=Math.floor(game.time/1000);$('timer').textContent=String(Math.floor(t/60)).padStart(2,'0')+':'+String(t%60).padStart(2,'0');$('attack').disabled=!started||paused||game.over||!game.boards[0].gauge;let e=game.events.at(-1);if(e&&game.time-e.time<1100){$('clash').classList.add('flash');$('clash').innerHTML=e.type==='mega'?'✷<br>보드 전체 폭발!':e.type==='expanded'?'✷<br>주변 두 겹 폭발!':e.type==='counter'?'↗ ✦ ↖<br>공격 상쇄!':e.type==='block'?'✧<br>방어 성공':e.i===0?'공격 발사 →':'← 공격이 옵니다'}else{$('clash').classList.remove('flash');$('clash').innerHTML='숫자를 모아<br>승부를 걸어라.'}}
function reset(play=true){audio.unlock();audio.stop();audio.play("start");cancelTouch();document.body.classList.remove("onboarding");game=new Game(Date.now(),Number($('difficulty').value));seenEvents.clear();flights=[];started=play;paused=false;soft=false;held={};$('result').close();$('startOverlay').style.display=play?'none':'flex';$('pause').textContent='Ⅱ';$('pause').disabled=!play;render()}
function pause(){audio.stop();cancelTouch();if(!started||game.over)return;paused=!paused;soft=false;held={};$('pause').textContent=paused?'▶':'Ⅱ';$('pause').setAttribute('aria-label',paused?'계속하기':'일시정지');let o=$('startOverlay');o.style.display=paused?'flex':'none';if(paused)o.innerHTML='<span class="mini-tile">Ⅱ</span><h2>잠시 쉬어가세요</h2><p>양쪽 보드가 멈췄습니다.</p><button class="primary" id="resume">계속하기 →</button>';if(paused)$('resume').onclick=pause}
$('start').onclick=()=>reset();$('restart').onclick=()=>showWelcome();$('again').onclick=()=>showWelcome();$('pause').onclick=pause;$('attack').onclick=()=>{if(started&&!paused)game.fire(0)};$('difficulty').onchange=()=>{game.speed=Number($('difficulty').value)};$('rulesBtn').onclick=()=>{rulePause=started&&!paused&&!game.over;if(rulePause)pause();$('rules').showModal()};$('closeRules').onclick=()=>$('rules').close();$('rules').onclose=()=>{if(rulePause){rulePause=false;pause()}};
window.addEventListener('keydown',e=>{if(document.body.classList.contains('onboarding'))return;if(['ArrowLeft','ArrowRight','ArrowDown','Space','Digit0','Numpad0'].includes(e.code)){if(document.body.classList.contains('onboarding')||touchPointer!==null||e.target instanceof HTMLSelectElement||$('rules').open||$('result').open)return;e.preventDefault();if(!started||paused||game.over)return;if(e.repeat)return;if(e.code==='ArrowLeft'||e.code==='ArrowRight'){game.move(0,e.code==='ArrowLeft'?-1:1);held[e.code]={time:0,next:180}}if(e.code==='ArrowDown')soft=true;if(e.code==='Space')game.drop(0);if(e.code==='Digit0'||e.code==='Numpad0')game.fire(0)}if(e.code==='Escape'&&!$('rules').open)pause()});window.addEventListener('keyup',e=>{delete held[e.code];if(e.code==='ArrowDown')soft=false});window.addEventListener('blur',()=>{soft=false;held={};if(started&&!paused&&!game.over)pause()});
function frame(now){let dt=Math.min(50,now-last||16);last=now;if(started&&!paused&&!game.over){for(let [key,v]of Object.entries(held)){v.time+=dt;if(v.time>=v.next){game.move(0,key==='ArrowLeft'?-1:1);v.next+=90}}game.tick(dt,soft);if(game.over){$('resultTitle').textContent=game.result;let s=game.boards[0].stats;$('resultStats').innerHTML=`플레이 시간 ${Math.floor(game.time/1000)}초<br>제거 ${s.clear}개 · 발사 ${s.sent}회<br>배치 방어 ${s.block}회 · 맞발사 ${s.counter}회`;audio.play(game.boards[0].dead?'lose':'win');$('result').showModal()}}render();drawFlights();requestAnimationFrame(frame)}$('pause').disabled=true;requestAnimationFrame(frame);

const flightCanvas=$('flightLayer'),fx=flightCanvas.getContext('2d');let flights=[],seenEvents=new Set();
function drawFlights(){let dpr=window.devicePixelRatio||1;if(flightCanvas.width!==Math.round(innerWidth*dpr)||flightCanvas.height!==Math.round(innerHeight*dpr)){flightCanvas.width=Math.round(innerWidth*dpr);flightCanvas.height=Math.round(innerHeight*dpr)}fx.setTransform(dpr,0,0,dpr,0,0);fx.clearRect(0,0,innerWidth,innerHeight);for(let e of game.events){if(seenEvents.has(e.id))continue;seenEvents.add(e.id);if(started&&!paused)audio.event(e);if(['fire','counter','mega','expanded'].includes(e.type))flights.push(e)}flights=flights.filter(e=>game.time-e.time<800);let rects=[$('board0').getBoundingClientRect(),$('board1').getBoundingClientRect()];let vertical=matchMedia('(max-width:650px)').matches;let middle=vertical?{x:rects[0].left+rects[0].width/2,y:(rects[1].bottom+rects[0].top)/2}:{x:(rects[0].right+rects[1].left)/2,y:rects[0].top+rects[0].height*.46};
const origin=i=>vertical?{x:rects[i].left+rects[i].width/2,y:i?rects[i].bottom:rects[i].top}:({x:i?rects[i].left-10:rects[i].right+10,y:rects[i].top+rects[i].height*.46});
function block(p,n,kind,alpha=1){fx.save();fx.globalAlpha=alpha;fx.translate(p.x,p.y);fx.shadowColor=kind==='pierce'?'#ae83cf':'#526c5555';fx.shadowBlur=kind==='pierce'?18:8;fx.fillStyle=ITEM_INFO[kind]?.color||colors[n]||'#d7e8da';fx.beginPath();fx.roundRect(-15,-17,30,34,7);fx.fill();fx.shadowBlur=0;fx.strokeStyle='#fff';fx.lineWidth=2;fx.stroke();fx.textAlign='center';fx.textBaseline='middle';fx.fillStyle=kind==='normal'||!kind?ink[n]:'#fff';fx.font='bold 20px sans-serif';fx.fillText(n,0,0);if(ITEM_INFO[kind]){fx.font='12px sans-serif';fx.fillText(ITEM_INFO[kind].mark,10,-14)}fx.restore()}
function burst(p,t,color){fx.save();fx.globalAlpha=Math.max(0,1-t);fx.strokeStyle=color;fx.lineWidth=3;for(let n=0;n<8;n++){let a=n*Math.PI/4,r=8+t*35;fx.beginPath();fx.moveTo(p.x+Math.cos(a)*r,p.y+Math.sin(a)*r);fx.lineTo(p.x+Math.cos(a)*(r+7),p.y+Math.sin(a)*(r+7));fx.stroke()}fx.restore()}
for(let e of flights){let age=game.time-e.time;if(e.type==='mega'||e.type==='expanded'){let r=rects[e.i],t=age/800;fx.save();fx.beginPath();fx.rect(r.left,r.top,r.width,r.height);fx.clip();fx.strokeStyle=e.type==='mega'?'#ddb160':'#b8c599';fx.globalAlpha=1-t;fx.lineWidth=8;for(let j=0;j<2;j++){fx.beginPath();fx.arc(r.left+r.width/2,r.top+r.height*.65,Math.max(0,t*r.height-j*65),0,Math.PI*2);fx.stroke()}fx.restore();continue}let from=origin(e.i),target=rects[1-e.i];let end={x:target.left+((e.x??3)+.5)*target.width/8,y:target.top+((e.y??8)+.5)*target.height/13};if(e.type==='counter'){let t=Math.min(1,age/300);if(t<1){for(let i of [0,1]){let a=origin(i);block({x:a.x+(middle.x-a.x)*t,y:a.y+(middle.y-a.y)*t-18*Math.sin(Math.PI*t)},i===e.i?e.n:e.otherN,'normal')}}else burst(middle,(age-300)/500,'#aa83bc');continue}if(e.type==='shield'){let r=rects[e.i];burst({x:e.i?r.left:r.right,y:r.top+r.height*.46},age/800,'#64ad9b');continue}if(e.type==='pierce'){burst(middle,age/800,'#ae83cf');continue}let duration=e.kind==='rush'?180:300,t=Math.min(1,age/duration);if(t<1){let pos={x:from.x+(end.x-from.x)*t,y:from.y+(end.y-from.y)*t-40*Math.sin(Math.PI*t)};fx.beginPath();fx.moveTo(from.x,from.y);fx.quadraticCurveTo((from.x+end.x)/2,Math.min(from.y,end.y)-40,pos.x,pos.y);fx.strokeStyle=e.kind==='pierce'?'#ae83cf88':'#a8c2ad66';fx.lineWidth=e.kind==='pierce'?5:2;fx.stroke();block(pos,e.n,e.kind)}else if(age<550)burst(end,(age-duration)/(550-duration),ITEM_INFO[e.kind]?.color||'#91b7a0')}
}

function cancelTouch(){touchColumn=null;touchPointer=null;touchActive=null}
function showWelcome(){audio.stop();cancelTouch();paused=true;soft=false;held={};$('result').close();document.body.classList.add('onboarding');$('welcome').scrollTop=0}
$('welcomeStart').onclick=()=>{let selected=document.querySelector('input[name="level"]:checked');$('difficulty').value=selected.value;reset();};
const touchBoard=$('board0');
function selectColumn(e){let r=touchBoard.getBoundingClientRect();touchColumn=Math.max(0,Math.min(7,Math.floor((e.clientX-r.left)/r.width*8)))}
touchBoard.addEventListener('pointerdown',e=>{if(!started||paused||game.over||game.boards[0].busy||!game.boards[0].active||touchPointer!==null)return;e.preventDefault();touchPointer=e.pointerId;touchActive=game.boards[0].active;selectColumn(e);touchBoard.setPointerCapture(e.pointerId)});
touchBoard.addEventListener('pointermove',e=>{if(e.pointerId===touchPointer){e.preventDefault();selectColumn(e)}});
touchBoard.addEventListener('pointerup',e=>{if(e.pointerId!==touchPointer)return;e.preventDefault();let r=touchBoard.getBoundingClientRect(),x=touchColumn,a=touchActive;cancelTouch();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)return;if(started&&!paused&&!game.over&&game.boards[0].active===a){if(!game.placeColumn(0,x))game.boards[0].note='이 열은 가득 찼어요. 다른 열을 선택하세요.'}});
touchBoard.addEventListener('pointercancel',cancelTouch);touchBoard.addEventListener('lostpointercapture',cancelTouch);
document.addEventListener('visibilitychange',()=>{if(document.hidden&&started&&!paused&&!game.over)pause()});

$('soundToggle').onclick=()=>{audio.toggle();$('soundToggle').textContent=audio.enabled?'♪':'♩̸';$('soundToggle').setAttribute('aria-label',audio.enabled?'소리 끄기':'소리 켜기');$('soundToggle').setAttribute('aria-pressed',String(audio.enabled))};
