export const W=8,H=13;
export function rng(seed){return()=>{seed|=0;seed=seed+0x6D2B79F5|0;let t=Math.imul(seed^seed>>>15,1|seed);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296}}
export const empty=()=>Array.from({length:H},()=>Array(W).fill(null));
export function oneGroups(g){let seen=new Set(),groups=[];for(let y=0;y<H;y++)for(let x=0;x<W;x++){let k=y*W+x;if(g[y][x]?.n!==1||seen.has(k))continue;let q=[k],cells=[];seen.add(k);while(q.length){let v=q.pop(),a=v%W,b=Math.floor(v/W);cells.push(v);for(let [c,d]of [[a-1,b],[a+1,b],[a,b-1],[a,b+1]])if(c>=0&&c<W&&d>=0&&d<H&&g[d][c]?.n===1&&!seen.has(d*W+c)){seen.add(d*W+c);q.push(d*W+c)}}groups.push(cells)}return groups.sort((a,b)=>b.length-a.length)}
export function largestOnes(g){return oneGroups(g)[0]||[]}
export function nextNumber(b){return 1+Math.floor(b.random()*9)}
export function matches(g){let same=new Set(),straight=new Set(),wide=new Set(),seen=new Set();const key=(x,y)=>y*W+x;for(let y=0;y<H;y++)for(let x=0;x<W;x++){let n=g[y][x]?.n,k=key(x,y);if(!n||n===1||seen.has(k))continue;let q=[[x,y]],cells=[];seen.add(k);while(q.length){let [a,b]=q.pop();cells.push(key(a,b));for(let [c,d]of [[a-1,b],[a+1,b],[a,b-1],[a,b+1]])if(c>=0&&c<W&&d>=0&&d<H&&g[d][c]?.n===n&&!seen.has(key(c,d))){seen.add(key(c,d));q.push([c,d])}}if(cells.length>=n)cells.forEach(v=>same.add(v))}
for(let y=0;y<H;y++)for(let x=0;x<W;x++)for(let [dx,dy]of [[1,0],[0,1]])for(let sign of [-1,1]){let cells=[],n=g[y][x]?.n;if(!n)continue;for(let a=x,b=y;a<W&&b<H&&g[b][a]?.n===n+sign*cells.length;a+=dx,b+=dy)cells.push(key(a,b));if(cells.length>=3){cells.forEach(v=>straight.add(v));if(cells.some(v=>g[Math.floor(v/W)][v%W].n===1))cells.forEach(v=>wide.add(v))}}
let removed=new Set([...same,...straight]);for(let k of straight){let x=k%W,y=Math.floor(k/W),radius=wide.has(k)?2:1;for(let dy=-radius;dy<=radius;dy++)for(let dx=-radius;dx<=radius;dx++){let a=x+dx,b=y+dy;if(Math.abs(dx)+Math.abs(dy)<=radius&&a>=0&&a<W&&b>=0&&b<H&&g[b][a])removed.add(b*W+a)}}return{same,straight,wide,removed}}
export function resolve(g,charge=true){let gain=0,count=0,lines=0,flash=[],mega=false,expanded=false;for(let loop=0;loop<128;loop++){if(largestOnes(g).length>=10){mega=true;for(let y=0;y<H;y++)for(let x=0;x<W;x++)if(g[y][x]){flash.push(y*W+x);count++;g[y][x]=null}break}let m=matches(g);expanded||=m.wide.size>0;if(!m.removed.size)break;gain+=charge?m.same.size:0;count+=m.removed.size;lines+=m.straight.size?1:0;flash.push(...m.removed);for(let k of m.removed)g[Math.floor(k/W)][k%W]=null;for(let x=0;x<W;x++){let col=[];for(let y=H-1;y>=0;y--)if(g[y][x])col.push(g[y][x]);for(let y=H-1;y>=0;y--)g[y][x]=col[H-1-y]||null}}return{gain,count,lines,flash,mega,expanded}}
export class Game{
constructor(seed=Date.now(),speed=450){this.seed=seed;this.random=rng(seed^991);this.speed=speed;this.time=0;this.id=0;this.events=[];this.over=false;this.boards=[0,1].map(()=>({g:empty(),random:rng(seed),active:null,gauge:0,incoming:[],fall:0,contact:0,ai:0,busy:0,dead:false,flash:[],note:'조합을 만들어 공격을 모으세요',stats:{gain:0,sent:0,block:0,counter:0,clear:0,straight:0}}));this.boards.forEach(b=>this.spawn(b))}
spawn(b){if(b.g[0][3]){b.dead=true;return}b.active={x:3,y:0,n:nextNumber(b)};b.fall=0;b.contact=0}
valid(b,x,y){return x>=0&&x<W&&y>=0&&y<H&&!b.g[y][x]}
landing(b,x,y=0){if(!this.valid(b,x,y))return -1;while(this.valid(b,x,y+1))y++;return y}
placeColumn(i,x){let b=this.boards[i];if(this.over||b.busy||!b.active||x<0||x>=W||b.g[0][x])return false;b.active.x=x;b.active.y=0;this.drop(i);return true}
move(i,dx){let b=this.boards[i],a=b.active;if(this.over||!a||b.busy)return;if(this.valid(b,a.x+dx,a.y)){a.x+=dx;if(this.valid(b,a.x,a.y+1))b.contact=0}}
down(i){let b=this.boards[i],a=b.active;if(!a||b.busy||this.over)return;if(this.valid(b,a.x,a.y+1)){a.y++;b.contact=0}}
drop(i){let b=this.boards[i];if(this.over||!b.active||b.busy)return;b.active.y=this.landing(b,b.active.x,b.active.y);this.lock(i)}
settle(b,charge){let r=resolve(b.g,charge);b.gauge=Math.min(20,b.gauge+r.gain);b.stats.gain+=r.gain;b.stats.clear+=r.count;b.stats.straight+=r.lines;if(r.count){b.flash=r.flash;b.busy=r.mega?700:r.expanded?380:220;b.note=r.mega?'1 열 개 연결! 보드 전체 폭발':r.expanded?'1 스트레이트! 주변 두 겹 폭발':r.lines?'스트레이트! 주변 타일 정리':`타일 ${r.count}개 제거 · 스택 +${r.gain}`}if(r.count&&!r.mega&&!r.expanded)this.event('clear',this.boards.indexOf(b));if(r.mega||r.expanded)this.event(r.mega?'mega':'expanded',this.boards.indexOf(b));this.checkTargets(b,r.mega);return r}
lock(i){let b=this.boards[i],a=b.active;if(!a)return;let hit=b.incoming.find(p=>p.y===a.y&&p.x===a.x&&p.remaining!==null);if(hit){this.remove(b,hit);b.stats.block++;b.note='배치 방어 성공!';this.event('block',i)}this.event('place',i);b.g[a.y][a.x]={n:a.n,attack:false};b.active=null;this.settle(b,true);if(!b.busy)this.spawn(b);this.finish()}
remove(b,p){b.incoming=b.incoming.filter(v=>v.id!==p.id)}
event(type,i,data={}){this.events.push({type,i,time:this.time,id:++this.id,...data});if(this.events.length>100)this.events.shift()}
fire(i){let b=this.boards[i],other=this.boards[1-i];if(this.over||b.busy||!b.gauge)return false;b.gauge--;let sorted=[...b.incoming].sort((a,c)=>(a.remaining??Infinity)-(c.remaining??Infinity)||a.id-c.id);if(sorted.length){this.remove(b,sorted[0]);b.stats.counter++;b.note='맞발사 · 공격 상쇄';this.event('counter',i,{n:1+Math.floor(this.random()*9),otherN:sorted[0].n});return true}let cols=Array.from({length:W},(_,x)=>x).filter(x=>!other.g[0][x]);if(!cols.length){other.dead=true;this.finish();return true}let x=cols[Math.floor(this.random()*cols.length)];other.incoming.push({id:++this.id,x,y:null,n:1+Math.floor(this.random()*9),remaining:null});b.stats.sent++;b.note='공격 발사!';this.activate(other);let p=other.incoming.at(-1);this.event('fire',i,{n:p.n,x:p.x,y:p.y});return true}
activate(b){for(let p of b.incoming){if(p.remaining!==null||b.incoming.some(q=>q.id!==p.id&&q.x===p.x&&q.remaining!==null))continue;if(b.g[0][p.x]){let cols=Array.from({length:W},(_,x)=>x).filter(x=>!b.g[0][x]&&!b.incoming.some(q=>q.remaining!==null&&q.x===x));if(!cols.length)continue;p.x=cols[Math.floor(this.random()*cols.length)]}p.y=this.landing(b,p.x);p.remaining=3000}}
checkTargets(b,reset=false){if(reset){for(let p of b.incoming){p.y=null;p.remaining=null}return}for(let p of [...b.incoming])if(p.remaining!==null&&(b.g[p.y][p.x]||(p.y<H-1&&!b.g[p.y+1][p.x]))){this.remove(b,p);b.note='지형 변화로 공격 방어';this.event('block',this.boards.indexOf(b))}}
impact(i,p){let b=this.boards[i];if(!b.incoming.includes(p))return;let a=b.active;if(a&&a.x===p.x&&a.y===p.y){this.drop(i);if(!b.incoming.includes(p))return}this.remove(b,p);if(!b.g[p.y][p.x]){b.g[p.y][p.x]={n:p.n,attack:true};this.settle(b,false);b.note='공격 도착 · 조합으로 제거하세요'}if(b.g[0][3])b.dead=true}
finish(){if(this.boards.some(b=>b.dead)){this.over=true;this.result=this.boards.every(b=>b.dead)?'무승부':this.boards[0].dead?'컴퓨터 승리':'승리!'}}
aiAct(){let b=this.boards[1],a=b.active;if(!a||b.busy)return;let urgent=b.incoming.some(p=>p.remaining!==null&&p.remaining<1100);if(b.gauge&&(urgent||b.gauge>2)){this.fire(1);return}let candidates=[];for(let x=0;x<W;x++){let path=true;for(let k=Math.min(x,a.x);k<=Math.max(x,a.x);k++)if(!this.valid(b,k,a.y))path=false;if(!path)continue;let y=this.landing(b,x,a.y);if(y<0)continue;let g=b.g.map(row=>row.map(t=>t&&{...t}));g[y][x]={n:a.n};let r=resolve(g);let height=0,max=0;for(let c=0;c<W;c++){let top=g.findIndex(row=>row[c]);let h=top<0?0:H-top;height+=h;max=Math.max(max,h)}let near=0;for(let [c,d]of [[x-1,y],[x+1,y],[x,y-1],[x,y+1]])if(c>=0&&c<W&&d>=0&&d<H&&g[d][c]?.n===a.n)near++;let block=b.incoming.some(p=>p.x===x&&p.y===y&&p.remaining!==null&&p.remaining>(Math.abs(a.x-x)+1)*this.speed);let score=(r.mega?150:0)+largestOnes(g).length*1.2+r.gain*3+r.count*2-height*.7-max*2+near*1.3-Math.abs(x-a.x)*.1+(block?22:0)-(g[0][3]?1000:0);candidates.push({x,score})}candidates.sort((x,y)=>y.score-x.score);let target=candidates[0];if(target){if(target.x!==a.x)this.move(1,Math.sign(target.x-a.x));else this.drop(1)}}
tick(dt,soft=false){if(this.over)return;this.time+=dt;for(let i=0;i<2;i++){let b=this.boards[i];if(b.busy){b.busy=Math.max(0,b.busy-dt);if(!b.busy){b.flash=[];if(!b.active)this.spawn(b)}continue}this.activate(b);for(let p of [...b.incoming])if(p.remaining!==null){p.remaining-=dt;if(p.remaining<=0)this.impact(i,p)}if(b.busy)continue;let a=b.active;if(a){b.fall+=dt;let interval=i===0&&soft?60:800;if(b.fall>=interval){b.fall%=interval;this.down(i)}if(!this.valid(b,a.x,a.y+1)){b.contact+=dt;if(b.contact>=300)this.lock(i)}else b.contact=0}if(i===1){b.ai+=dt;if(b.ai>=this.speed){b.ai=0;this.aiAct()}}}this.finish()}
}
