import {empty,resolve} from './tiles-engine.mjs';
import {audio} from './sound.mjs';
const $=id=>document.getElementById(id),key='numbers-war-tutorial-v1';
let step=0,part=0,done=false,locked=false,active=false,grid=empty(),enemy=empty(),target=3,number=2,preview=null,timers=[],animations=[],pointer=null,column=null,defending=false;
const titles=['같은 숫자 모으기','공격 스택으로 발사','스트레이트 만들기','배치로 방어하기','맞발사로 방어하기','1의 특별한 폭발','승리 조건'];
function later(fn,ms){timers.push(setTimeout(()=>{if(active)fn()},ms))}
function clean(){timers.forEach(clearTimeout);timers=[];animations.forEach(a=>a.cancel());animations=[];$('tFx').replaceChildren();pointer=null;column=null}
function message(t){$('tMessage').textContent=t}
function cell(board,x,y){return $(board).children[(y-(board==='tEnemy'?9:7))*8+x]}
function renderBoard(id,g,start){let b=$(id);b.replaceChildren();for(let y=start;y<13;y++)for(let x=0;x<8;x++){let t=g[y][x],e=document.createElement('div');e.className='t-cell'+(t?' t-n'+t.n:'');e.textContent=t?.n||'';if(id==='tBoard'&&!done&&![1,4,6].includes(step)&&x===target)e.classList.add('t-selected');if(preview&&preview.board===id&&x===preview.x&&y===preview.y){e.textContent=preview.n;e.className+=' t-n'+preview.n+' t-warning';e.style.opacity=String(.2+.7*(1-preview.left/3000));let label=document.createElement('small');label.textContent=(preview.left/1000).toFixed(1);e.append(label)}b.append(e)}}
function draw(){renderBoard('tEnemy',enemy,9);renderBoard('tBoard',grid,7);$('tHeld').textContent=number;$('tHeld').className='t-held t-n'+number;$('tHeld').hidden=[1,4,6].includes(step)||done;$('tOpponent').hidden=![1,3,4,6].includes(step);$('tEnemy').hidden=![1,3,4,6].includes(step)}
function fly(from,to,n,collision=false){let a=from.getBoundingClientRect(),b=to.getBoundingClientRect(),x=a.left+a.width/2,y=a.top+a.height/2,ex=b.left+b.width/2,ey=b.top+b.height/2;let trail=document.createElement('div');trail.className='t-trail';Object.assign(trail.style,{left:x+'px',top:y+'px',width:Math.hypot(ex-x,ey-y)+'px',transform:'rotate('+Math.atan2(ey-y,ex-x)+'rad)'});$('tFx').append(trail);let tile=document.createElement('div');tile.className='t-projectile t-n'+n;tile.textContent=n;Object.assign(tile.style,{left:(x-16)+'px',top:(y-18)+'px'});$('tFx').append(tile);animations.push(tile.animate([{transform:'translate(0,0)'},{transform:`translate(${(ex-x)/2+12}px,${(ey-y)/2}px)`},{transform:`translate(${ex-x}px,${ey-y}px)`}],{duration:300,fill:'forwards',easing:'ease-out'}));later(()=>{tile.remove();trail.remove();if(collision){let p=document.createElement('span');p.className='t-spark';p.textContent='✦';p.style.left=(ex-18)+'px';p.style.top=(ey-20)+'px';$('tFx').append(p);animations.push(p.animate([{transform:'scale(.4)',opacity:1},{transform:'scale(2)',opacity:0}],{duration:350,fill:'forwards'}));later(()=>p.remove(),350)}},300)}
function success(text,sound='clear'){done=true;locked=false;defending=false;preview=null;timers.forEach(clearTimeout);timers=[];message(text);$('tNext').disabled=false;$('tFire').disabled=true;$('tReady').hidden=true;$('tCount').textContent='성공!';audio.play(sound);draw()}
function setup(){clean();$('tReady').onclick=incoming;done=false;locked=false;defending=false;preview=null;grid=empty();enemy=empty();number=2;target=3;$('tTitle').textContent=titles[step];$('tProgress').textContent=(step+1)+' / 7';$('tNext').disabled=true;$('tNext').textContent=step===6?'난이도 선택 →':'다음 →';$('tPrev').disabled=step===0&&part===0;$('tReady').hidden=![3,4].includes(step);$('tReady').textContent='준비됐어요 · 공격 받기';$('tFire').hidden=![1,4,6].includes(step);$('tFire').disabled=step===4;$('tFire').textContent=step===6?'승리 장면 보기':'↑ 공격 보내기';$('tCount').textContent='';$('tMeter').textContent=[1,4].includes(step)?'공격 스택 2/20':'공격 스택 0/20';$('tOpponent').textContent='상대방(Ai)';message('반짝이는 열을 눌렀다가 손을 떼세요.');
if(step===0){number=part+2;if(part===0)grid[12][2]={n:2};if(part===1){grid[12][1]={n:3};grid[12][2]={n:3}}if(part===2){grid[12][2]={n:4};grid[11][2]={n:4};grid[12][3]={n:4}}$('tHint').textContent=number+'는 '+number+'개가 붙으면 사라져요. 마지막 하나를 놓아보세요. ('+(part+1)+'/3)'}
if(step===1){$('tHint').textContent='공격 버튼을 누르고, 상대에게 도착하는 모습을 보세요.';message('비행 → 3초 예고 → 고정 타일');enemy[12][4]={n:8}}
if(step===2){grid[12][2]={n:3};grid[12][3]={n:4};grid[12][5]={n:9};grid[11][2]={n:8};number=5;target=4;$('tHint').textContent='3–4 다음에 5! 한 줄로 연속 숫자 3개를 놓으세요.'}
if(step===3){number=6;$('tHint').textContent='공격이 오면, 흐린 타일이 있는 열에 내 타일을 놓으세요.';message('준비 버튼을 누르면 실제 3초 예고가 시작돼요.')}
if(step===4){$('tHint').textContent='공격이 오면 공격 버튼을 눌러 맞발사하세요.';message('스택 1칸으로 상대 공격 1개를 막을 수 있어요.')}
if(step===5){if(!part){grid[12][2]={n:1};grid[12][3]={n:2};grid[12][5]={n:8};grid[11][5]={n:9};grid[10][3]={n:7};number=3;target=4;$('tHint').textContent='1–2–3 스트레이트는 주변 두 겹까지 터져요.'}else{for(let x=0;x<8;x++)grid[12][x]={n:1};grid[11][0]={n:1};number=1;target=1;$('tHint').textContent='연결된 1이 아홉 개! 하나 더 붙여 전체 폭발을 만드세요.'}}
if(step===6){for(let y=9;y<13;y++)enemy[y][3]={n:y%2?8:9};$('tHint').textContent='상대의 타일 생성 위치가 막히면 승리해요.';$('tOpponent').textContent='상대 생성 위치 ↓';message('상대 보드의 맨 위를 확인하세요.')}
draw()}
function countdown(onEnd){let start=performance.now();function tick(){if(!preview||done)return;preview.left=Math.max(0,3000-(performance.now()-start));$('tCount').textContent=(preview.left/1000).toFixed(1)+'초';draw();if(preview.left<=0)onEnd();else later(tick,40)}tick()}
function incoming(){if(locked||done||defending)return;audio.unlock();defending=true;$('tReady').hidden=true;$('tFire').disabled=false;preview={board:'tBoard',x:3,y:12,n:7,left:3000};draw();fly(cell('tEnemy',3,10),cell('tBoard',3,12),7);audio.play('fire',true);countdown(()=>{grid[12][3]={n:7};preview=null;locked=true;defending=false;draw();message('공격이 도착했어요. 준비되면 다시 해보세요.');$('tReady').hidden=false;$('tReady').textContent='다시 연습';$('tFire').disabled=true;$('tReady').onclick=()=>{setup();incoming()}})}
$('tReady').onclick=incoming;
function place(x){if(!active||done||locked||[1,4,6].includes(step)||step===3&&!defending)return;if(x!==target){message('반짝이는 열에 놓아볼까요?');return}let y=12;while(y>=7&&grid[y][x])y--;grid[y][x]={n:number};locked=true;audio.play('place');if(step===3){preview=null;timers.forEach(clearTimeout);timers=[];animations.forEach(a=>a.cancel());$('tFx').replaceChildren();success('배치 방어! 상대 예고는 사라지고 내 6은 남아요.','block');return}draw();later(()=>{let r=resolve(grid);$('tMeter').textContent='공격 스택 +'+r.gain;success(step===0?number+'개 제거 → 스택 '+r.gain+'칸!'+(part===2?' 꺾인 모양도 연결돼요.':''):step===2?'스트레이트! 주변 한 겹도 제거돼요. 세로·역순도 가능해요.':part?'연결된 1 열 개! 내 보드 전체 폭발!':'1 스트레이트! 주변 두 겹까지 제거돼요.',step===5?(part?'mega':'expanded'):'clear')},400)}
$('tFire').onclick=()=>{if(done||locked||step===4&&!defending)return;audio.unlock();if(step===6){success('승리! 내 생성 위치가 막히지 않도록 조심하세요.','win');return}locked=true;$('tFire').disabled=true;$('tMeter').textContent='공격 스택 1/20';if(step===1){preview={board:'tEnemy',x:4,y:11,n:6,left:3000};draw();fly(cell('tBoard',3,10),cell('tEnemy',4,11),6);audio.play('fire');countdown(()=>{enemy[11][4]={n:6};preview=null;success('3초 후 상대 보드에 공격 타일이 쌓였어요.','place')})}else{preview=null;timers.forEach(clearTimeout);timers=[];animations.forEach(a=>a.cancel());$('tFx').replaceChildren();draw();fly(cell('tBoard',3,10),$('tFlight'),6,true);fly(cell('tEnemy',3,10),$('tFlight'),7);audio.play('fire');later(()=>{audio.play('counter')},300);later(()=>success('맞발사! 스택 1칸과 상대 공격 1개가 함께 사라졌어요.','counter'),700)}};
const board=$('tBoard');function col(e){let r=board.getBoundingClientRect();return Math.min(7,Math.max(0,Math.floor((e.clientX-r.left)/r.width*8)))}board.addEventListener('pointerdown',e=>{if(done||locked||pointer!==null)return;audio.unlock();pointer=e.pointerId;column=col(e);board.setPointerCapture(pointer);e.preventDefault()});board.addEventListener('pointermove',e=>{if(e.pointerId===pointer)column=col(e)});board.addEventListener('pointerup',e=>{if(pointer!==e.pointerId)return;let r=board.getBoundingClientRect(),x=column;pointer=null;if(e.clientX>=r.left&&e.clientX<=r.right&&e.clientY>=r.top&&e.clientY<=r.bottom)place(x)});board.addEventListener('pointercancel',()=>{pointer=null});
function exit(){clean();active=false;audio.stop();$('tutorial').hidden=true;try{localStorage.setItem(key,'seen')}catch{}$('welcomeStart').focus()}
function open(){active=true;step=0;part=0;$('tutorial').hidden=false;setup();$('tSkip').focus()}
$('tSkip').onclick=exit;$('tNext').onclick=()=>{if(!done)return;if(step===0&&part<2||step===5&&part===0){part++;setup();return}part=0;if(step===6)exit();else{step++;setup()}};$('tPrev').onclick=()=>{if(part)part--;else{step=Math.max(0,step-1);part=step===0?2:step===5?1:0}setup()};$('tutorialReplay').onclick=open;let seen=false;try{seen=localStorage.getItem(key)==='seen'}catch{}if(!seen)open();
